"""
Script: rank_patients_by_dsc.py

Description:
    Analyses the individual results of each patient within a specific experimental
    configuration and, for each available enhancement algorithm, determines which
    patients obtained the best and worst DSC, also indicating the plane on which
    that metric was obtained (excluding the consensus plane).

    This script scans the tree:

    results/<enhancement>/<modality>_<num_slices>slices_<k_folds>folds_<epochs>epochs/foldX/PX/PX_<plane>_results.json

    where each file corresponds to a patient in a given plane and contains individual
    metrics generated by `eval.py`.

Execution mode:
    This script must be run via CLI only. It is not part of the pipeline and is not
    prepared for internal use.

CLI Arguments:
    --plane (str, required)
        Anatomical plane of the model ('axial', 'coronal', 'sagital').
        Used only to build the Model object.

    --modality (list[str], optional)
        MRI modality or modalities ('T1', 'T2', 'FLAIR').
        Defaults to all. Used to locate the experiment.

    --num_slices (int_or_percentile, required)
        Number of extracted slices (integer value or percentile, e.g. 50 or 'P50').

    --enhancement (str, optional)
        Image enhancement algorithm applied ('HE', 'CLAHE', 'GC', 'LT', or None).
        Defaults to None. Does not affect filtering; used only to locate the experiment.

    --epochs (int, required)
        Number of epochs of the trained model.

    --k_folds (int, optional)
        Number of folds used in cross-validation.
        Defaults to 5.

CLI Usage:
    python -m yolo_mslesseg.extras.rank_patients_by_dsc \\
        --plane axial \\
        --modality FLAIR \\
        --num_slices P50 \\
        --epochs 50

Inputs:
    - Per-patient JSON files: PX_<plane>_results.json

Outputs:
    - Console output: best and worst patient for each enhancement algorithm.
"""

import argparse
from pathlib import Path

from yolo_mslesseg.utils.Model import Model
from yolo_mslesseg.utils.logging_config import get_logger
from yolo_mslesseg.utils.constants import ANATOMICAL_PLANES, EXT_JSON, RESULTS_DIR
from yolo_mslesseg.utils.utils import (
    path_exists,
    read_json,
    int_or_percentile,
    build_config_name,
)

logger = get_logger(__file__)

# ======================================
#           BASE FUNCTIONS
# ======================================


def extract_plane_from_json(json_path: Path) -> str | None:
    """Extracts the anatomical plane label from a per-patient results JSON filename.

    Args:
        json_path: Path to a patient results JSON file named PX_<plane>_results.json.

    Returns:
        Plane string if found in the filename, or None if the plane is unknown or
        corresponds to the consensus.
    """
    stem = json_path.stem  # e.g. "P1_axial_results"

    # Skip consensus
    if "consenso" in stem:
        return None

    for plane in ANATOMICAL_PLANES:
        if (
            f"_{plane}_" in stem
            or stem.endswith(f"_{plane}")
            or stem.startswith(f"{plane}_")
        ):
            return plane

    return None


def extract_patient_dsc(json_path: Path) -> float | None:
    """Extracts the DSC value from an individual patient JSON file.

    Args:
        json_path: Path to the patient results JSON file.

    Returns:
        DSC value as a float, or None if the file could not be read or DSC is absent.
    """
    try:
        data = read_json(json_path)
    except Exception as e:
        logger.warning(f"⚠️ Could not read {json_path}: {e}")
        return None

    return data.get("DSC", None)


def print_results(dsc_per_enhancement: dict[str, dict]) -> None:
    """Prints the best and worst patient per enhancement algorithm to the console.

    Args:
        dsc_per_enhancement: Nested dictionary mapping enhancement labels to
            patient dictionaries with 'dsc' and 'plane' values.
    """
    for enhancement, patients_info in dsc_per_enhancement.items():
        if not patients_info:
            logger.info(f"ℹ️ Enhancement {enhancement} has no data.")
            continue

        # Best / worst by DSC
        best = max(patients_info, key=lambda px: patients_info[px]["dsc"])
        worst = min(patients_info, key=lambda px: patients_info[px]["dsc"])

        print(f"\n===== {enhancement} =====")
        print(
            f"  Best patient:  {best} "
            f"(DSC = {patients_info[best]['dsc']:.4f}, "
            f"plane = {patients_info[best]['plane']})"
        )
        print(
            f"  Worst patient: {worst}  "
            f"(DSC = {patients_info[worst]['dsc']:.4f}, "
            f"plane = {patients_info[worst]['plane']})"
        )


def analyze_experiment(results_dir: Path, global_config: str) -> None:
    """Traverses the results directory tree and ranks patients by DSC per enhancement.

    Args:
        results_dir: Root results directory to scan.
        global_config: Configuration string used to locate experiment subdirectories.
    """
    if not path_exists(results_dir):
        logger.error(f"❌ Results directory does not exist: {results_dir}")
        return

    dsc_per_enhancement = {}

    # Iterate over enhancement directories
    for enhancement_dir in results_dir.iterdir():
        if not enhancement_dir.is_dir():
            continue

        enhancement = enhancement_dir.name.upper()
        experiment_dir = enhancement_dir / global_config

        if not experiment_dir.exists():
            continue

        dsc_per_enhancement.setdefault(enhancement, {})

        # Iterate over folds or test group (k_folds == 1)
        for group_dir in experiment_dir.iterdir():
            if not group_dir.is_dir():
                continue

            # Accept foldX or test
            if not (group_dir.name.startswith("fold") or group_dir.name == "test"):
                continue

            # Patients
            for px_dir in group_dir.iterdir():
                if not px_dir.is_dir():
                    continue

                patient_id = px_dir.name

                # Individual patient JSON files
                for json_file in px_dir.glob(f"*{EXT_JSON}"):
                    plane = extract_plane_from_json(json_file)
                    if plane not in ANATOMICAL_PLANES:
                        continue  # Skip consensus or unknown planes

                    dsc = extract_patient_dsc(json_file)
                    if dsc is None:
                        continue

                    # Keep if better than previously stored
                    previous = dsc_per_enhancement[enhancement].get(patient_id, None)
                    if previous is None or dsc > previous["dsc"]:
                        dsc_per_enhancement[enhancement][patient_id] = {
                            "dsc": dsc,
                            "plane": plane,
                        }

    if not dsc_per_enhancement:
        logger.warning("⚠️ No individual metrics found.")
        return

    print_results(dsc_per_enhancement)


# ======================================
#               MAIN FLOW
# ======================================


def run_flow(model: Model, epochs: int) -> None:
    """Executes the full patient analysis flow.

    Args:
        model: Model instance used to derive the experiment configuration string.
        epochs: Number of training epochs of the YOLO model.
    """
    global_config = build_config_name(model, epochs)

    logger.header(f"🔍 Analysing patients for {global_config}")

    analyze_experiment(
        results_dir=RESULTS_DIR, global_config=global_config
    )


# ======================================
#          CLI AND EXECUTION
# ======================================


def parse_args() -> argparse.Namespace:
    """Parses the CLI arguments.

    Returns:
        Namespace with the parsed CLI arguments.
    """
    parser = argparse.ArgumentParser(
        description="Analyse best and worst patients per enhancement algorithm based on DSC."
    )
    parser.add_argument(
        "--plane",
        type=str,
        required=True,
        choices=["axial", "coronal", "sagital"],
        metavar="[axial, coronal, sagital]",
        help="Anatomical plane of the model.",
    )
    parser.add_argument(
        "--modality",
        nargs="+",
        choices=["T1", "T2", "FLAIR"],
        default=["T1", "T2", "FLAIR"],
        metavar="[T1, T2, FLAIR]",
        help="MRI modality or modalities. Defaults to all.",
    )
    parser.add_argument(
        "--num_slices",
        type=int_or_percentile,
        required=True,
        metavar="<num_slices>",
        help="Number of extracted slices (fixed value or percentile).",
    )
    parser.add_argument(
        "--enhancement",
        type=str,
        default=None,
        choices=["HE", "CLAHE", "GC", "LT"],
        metavar="<enhancement>",
        help="Image enhancement algorithm applied. Defaults to None.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        required=True,
        metavar="<epochs>",
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--k_folds",
        type=int,
        default=5,
        metavar="<k_folds>",
        help="Number of folds for cross-validation. Defaults to 5.",
    )
    return parser.parse_args()


def main() -> None:
    """CLI entry point: parses arguments, builds the Model instance, and executes the full flow."""
    args = parse_args()

    model = Model(
        plane=args.plane,
        num_slices=args.num_slices,
        modality=args.modality,
        k_folds=args.k_folds,
        enhancement=args.enhancement,
    )

    run_flow(model=model, epochs=args.epochs)


if __name__ == "__main__":
    main()
