from pathlib import Path

from yolo_mslesseg.utils.logging_config import get_logger
from yolo_mslesseg.utils.Model import Model
from yolo_mslesseg.utils.constants import (
    DATASETS_DIR,
    SPLIT_TRAIN,
    TRAINS_DIR,
    WEIGHTS_FILE,
    EXT_YAML,
    SPLIT_TEST,
)
from yolo_mslesseg.utils.utils import (
    path_exists,
    create_directory,
    delete_directory,
)

logger = get_logger(__file__)


class ConfigTrain:
    """
    Class: ConfigTrain

    Description:
        Configuration and path management for the YOLO model training stage,
        implemented in `train.py`. Handles verification, creation, and cleanup
        of directories associated with the experiment, ensuring dataset
        availability and the YAML file required for a correct model training run.

        Supports two schemes:
            - k_folds > 1: cross-validation, training one model per fold.
            - k_folds == 1: single training run without fold subdirectories.

    Directory conventions:
        datasets/: YOLO dataset generated by `extract_dataset.py`

        - k_folds > 1
            datasets/<base_path>/
                └── fold1/ ... foldK/
                    └── PX/
                        └── <plane>/
                            ├── images/
                            ├── labels/
                            └── GT_masks/

        - k_folds == 1
            datasets/<base_path>/
                ├── train/
                │   └── <plane>/
                │       └── PX/
                │           ├── images/
                │           ├── labels/
                │           └── GT_masks/
                └── test/
                    └── <plane>/
                        └── PX/
                            ├── images/
                            ├── labels/
                            └── GT_masks/

        trains/: YOLO training results

        - k_folds > 1
            trains/<base_path>_<epochs>epochs/<plane>/
                └── fold<fold_test>/
                    ├── weights/
                    ├── results.csv
                    └── ...

        - k_folds == 1
            trains/<base_path>_<epochs>epochs/<plane>/
                ├── weights/
                ├── results.csv
                └── ...

        yaml_files/: YAML files generated for YOLO
            datasets/yaml_files/

    Attributes:
        model (Model):
            Model instance defining the plane, modalities, enhancement, and base_path.

        plane (str):
            Anatomical processing plane ('axial', 'coronal', or 'sagittal').

        epochs (int):
            Number of training epochs.

        fold_test (int | None, optional):
            Fold used as the test set (1, ..., k_folds).
            Only applies when k_folds > 1.

        dataset_base_dir (Path):
            Base dataset directory: datasets/<base_path>/.

        train_output_dir (Path):
            Training output directory: trains/<base_path>_<epochs>epochs/<plane>/.

        model_path (Path):
            Path to the trained model weights:
                - k_folds > 1: .../<fold>/weights/best.pt
                - k_folds == 1: .../weights/best.pt

        yaml_path (Path):
            Path to the YOLO YAML file:
                - k_folds > 1: dataset_<model_string>_fold<fold_test>.yaml
                - k_folds == 1: dataset_<model_string>.yaml

        weights_path (Path):
            Path to the base YOLO model weights.
    """

    def __init__(self, model: Model, epochs: int, fold_test: int | None = None) -> None:
        """Initialises a ConfigTrain instance for the model training stage.

        Args:
            model: Model instance defining the plane, modalities, and base_path.
            epochs: Number of training epochs.
            fold_test: Test fold index when using cross-validation, or None for
                k_folds == 1.

        Raises:
            ValueError: If fold_test is inconsistent with k_folds.
        """
        self._set_main_attributes(model, epochs, fold_test)
        self._resolve_dataset_paths()
        self._resolve_output_paths()

    # ======================================
    #         CONSTRUCTOR HELPERS
    # ======================================

    def _set_main_attributes(self, model: Model, epochs: int, fold_test: int | None) -> None:
        """Sets the core attributes and validates fold_test against k_folds.

        Args:
            model: Model instance.
            epochs: Number of training epochs.
            fold_test: Test fold index, or None when k_folds == 1.

        Raises:
            ValueError: If fold_test and k_folds are inconsistent.
        """
        self.model = model
        self.plane = model.plane
        self.epochs = epochs
        self.fold_test = fold_test

        self.single_fold = self.model.k_folds == 1

        if self.single_fold:
            if self.fold_test is not None:
                raise ValueError("fold_test must not be specified when k_folds == 1.")
        else:
            if self.fold_test is None:
                raise ValueError("fold_test must be specified when k_folds > 1.")

    def _resolve_dataset_paths(self) -> None:
        """Resolves all input dataset directory paths based on k_folds and fold_test."""
        # Base directory
        self.dataset_base_dir = DATASETS_DIR / f"{self.model.base_path}"

        if self.single_fold:
            self.train_dir = self.dataset_base_dir / SPLIT_TRAIN
            self.test_dir = self.dataset_base_dir / SPLIT_TEST

            # Temporary flat YOLO directories (flat structure with images/ and labels/)
            self.fold_train_dir = self.dataset_base_dir / "train_yolo" / self.plane
            self.fold_test_dir = self.dataset_base_dir / "test_yolo" / self.plane
            return

        # Fold directory in the dataset
        self.fold_dir = self.dataset_base_dir / f"fold{self.fold_test}"

        # Specific train/test split directories for each fold
        self.fold_train_dir = (
            self.dataset_base_dir / f"train_fold{self.fold_test}" / self.plane
        )

        self.fold_test_dir = (
            self.dataset_base_dir / f"test_fold{self.fold_test}" / self.plane
        )

    def _resolve_output_paths(self) -> None:
        """Resolves the training output, YAML, model weights, and base weights paths."""
        self.train_output_dir = (
            TRAINS_DIR / f"{self.model.base_path}_{self.epochs}epochs" / self.plane
        )

        if self.single_fold:
            self.yaml_path = (
                DATASETS_DIR
                / "yaml_files"
                / f"dataset_{self.model.model_string}{EXT_YAML}"
            )
            self.model_path = self.train_output_dir / "weights" / WEIGHTS_FILE
        else:
            self.yaml_path = (
                Path("datasets")
                / "yaml_files"
                / f"dataset_{self.model.model_string}_fold{self.fold_test}{EXT_YAML}"
            )
            self.model_path = (
                self.train_output_dir
                / f"fold{self.fold_test}"
                / "weights"
                / WEIGHTS_FILE
            )

        self.weights_path = Path("yolo11n-seg.pt")

    # ======================================
    #              CLEANUP
    # ======================================

    def clean_training(self) -> None:
        """Cleans the training results for the current configuration.

        When k_folds > 1, removes only the current fold's subdirectory.
        When k_folds == 1, removes the full experiment directory for the plane.
        """
        if not path_exists(self.train_output_dir):
            return

        if self.single_fold:
            delete_directory(self.train_output_dir)
            return

        fold_dir = self.train_output_dir / f"fold{self.fold_test}"
        if path_exists(fold_dir):
            delete_directory(fold_dir)

    # ======================================
    #            VERIFICATION
    # ======================================

    def verify_paths(self) -> None:
        """Verifies that input and output directories exist for YOLO model training.

        Checks that the dataset base directory exists, and creates the YAML and
        training output directories if they do not.

        Raises:
            FileNotFoundError: If the dataset base directory does not exist.
        """
        # dataset_base_dir
        if not path_exists(self.dataset_base_dir):  # Raises exception if not found
            raise FileNotFoundError(
                f"Dataset base directory not found: {self.dataset_base_dir}"
            )

        # yaml_dir
        yaml_dir = self.yaml_path.parent
        create_directory(yaml_dir)

        # train_output_dir
        create_directory(self.train_output_dir)  # Ensure output directory exists

    # ======================================
    #            REPRESENTATION
    # ======================================

    def __repr__(self) -> str:
        """String representation of this ConfigTrain instance."""
        if self.single_fold:
            return f"{self.__class__.__name__}(model={self.model.model_string}, epochs={self.epochs}, k_folds=1)"
        return f"{self.__class__.__name__}(model={self.model.model_string}, fold={self.fold_test}, epochs={self.epochs})"
