"""
Script: reconstruct_volume.py

Description:
    Reconstructs 3D NIfTI volumes from the 2D prediction masks generated by the
    YOLO model, either for an individual patient or for all patients in a fold.
    Reconstructed volumes are automatically validated against the ground truth
    masks and stored in the pred_vols/ directory.

Execution modes:
    1. CLI (standalone):
       - Arguments are read and parsed from the command line.
       - Model and (optionally) Patient instances are created.

    2. Internal (from `run_pipeline.py`):
       - Pre-built Model and (optionally) Patient instances are received,
         along with the remaining parameters.
       - The argument parser is not used.

CLI Usage:
    python -m yolo_mslesseg.scripts.reconstruct_volume \
        --plane sagittal \
        --num_slices P75 \
        --epochs 25 \
        --fold_test 1

Inputs:
    - Predicted 2D masks (.png): generated previously with `generate_predictions.py`,
        in the pred_masks/ subdirectory within each patient.

    - Ground truth (.nii.gz): original volumes located in GT/<patient_id>/
        used as reference for reconstruction and validation.

    - Classes:
        * ConfigReconstruction → manages paths and global variables for reconstruction.
        * Model                → defines the plane, modalities, enhancement, and num_slices.

Outputs:
    - Reconstructed volumes (.nii.gz) in
    pred_vols/<enhancement>/<modality>_<num_slices>slices_<k_folds>folds_<epochs>epochs/<fold_test>/PX/
"""

import argparse
import re
import sys
from pathlib import Path

import numpy as np
from PIL import Image

from yolo_mslesseg.configs.ConfigReconstruction import ConfigReconstruction
from yolo_mslesseg.utils.Model import Model
from yolo_mslesseg.utils.Patient import Patient
from yolo_mslesseg.utils.logging_config import get_logger
from yolo_mslesseg.utils.constants import EXT_PNG, EXT_NIFTI, MASK_SUFFIX, ENHANCEMENTS, StageResult
from yolo_mslesseg.utils.utils import (
    save_volume,
    int_or_percentile,
    path_exists,
    list_patients,
    load_nifti_reference,
    evaluate_results,
    is_valid_reconstruction,
    log_fold_status,
)

# Configure logger
logger = get_logger(__file__)


# ======================================
#              BASE FUNCTIONS
# ======================================


def extract_png_indices(input_dir: Path) -> list[tuple[str, int]]:
    """Extracts numeric slice indices from PNG filenames in a directory.

    Args:
        input_dir: Directory containing the predicted mask PNG files.

    Returns:
        Sorted list of (filename, index) tuples ordered by slice index.

    Raises:
        FileNotFoundError: If input_dir does not exist or contains no matching PNG files.
    """
    if not path_exists(input_dir):
        raise FileNotFoundError(
            f"Predicted masks directory not found: {input_dir}"
        )

    pattern = re.compile(r".*_(\d+)(?:_[^_]*)?\.png$", re.IGNORECASE)
    tuples = []

    for p in input_dir.glob(f"*{EXT_PNG}"):
        m = pattern.match(p.name)
        if m:
            tuples.append((p.name, int(m.group(1))))
        else:
            logger.warning(f"⚠️ Could not extract index from {p.name}")

    if not tuples:
        raise FileNotFoundError("No predicted masks to process.")

    # Sort by index
    tuples.sort(key=lambda t: t[1])
    return tuples


def load_and_preprocess_image(img_path: Path) -> np.ndarray:
    """Loads a PNG image, converts it to greyscale, and binarises it if necessary.

    Args:
        img_path: Path to the PNG image file.

    Returns:
        2D float32 array with binary values (0 or 1).

    Raises:
        FileNotFoundError: If the image file does not exist.
    """
    if not path_exists(img_path):
        raise FileNotFoundError(f"Image not found: {img_path}")

    img = Image.open(img_path)
    img_array = np.array(img)

    if len(img_array.shape) > 2:  # RGB → greyscale
        img_array = img_array[:, :, 0]

    if np.max(img_array) > 1:  # Binarise if not already normalised
        img_array = (img_array > 0).astype(np.float32)

    return img_array


def validate_slice(idx: int, img_array: np.ndarray, shape_original: tuple[int, ...], plane: str) -> None:
    """Validates that a slice index and its dimensions are consistent with the reference volume.

    Args:
        idx: Slice index within the volume.
        img_array: 2D slice array to validate.
        shape_original: Shape of the reference NIfTI volume (x, y, z).
        plane: Anatomical plane ('axial', 'coronal', 'sagittal').

    Raises:
        ValueError: If the index is out of range or the slice dimensions are incorrect.
    """
    # 1. Validate index is within range
    max_indices = {
        "axial": shape_original[2],
        "coronal": shape_original[1],
        "sagittal": shape_original[0],
    }
    if idx < 0 or idx >= max_indices[plane]:
        raise ValueError(f"Index {idx} out of range for plane {plane}.")

    # 2. Validate slice dimensions
    expected_shapes = {
        "axial": (shape_original[0], shape_original[1]),
        "coronal": (shape_original[0], shape_original[2]),
        "sagittal": (shape_original[1], shape_original[2]),
    }
    if img_array.shape != expected_shapes[plane]:
        raise ValueError(
            f"Dimensions {img_array.shape} are incorrect for plane {plane}. "
            f"Expected {expected_shapes[plane]}."
        )


def insert_slice(volume: np.ndarray, img_array: np.ndarray, idx: int, plane: str) -> None:
    """Inserts a 2D slice into the correct position of a 3D volume for the given plane.

    Args:
        volume: 3D NumPy array to insert the slice into (modified in-place).
        img_array: 2D slice array to insert.
        idx: Slice index along the axis corresponding to the plane.
        plane: Anatomical plane ('axial', 'coronal', 'sagittal').
    """
    if plane == "axial":
        volume[:, :, idx] = img_array
    elif plane == "coronal":
        volume[:, idx, :] = img_array
    elif plane == "sagittal":
        volume[idx, :, :] = img_array


# ======================================
#          3D RECONSTRUCTION
# ======================================


def needs_reconstruction(pred_path: Path) -> bool:
    """Checks whether a reconstructed volume needs to be (re)generated.

    Args:
        pred_path: Path to the predicted NIfTI volume file.

    Returns:
        True if the file does not exist or has zero size, False otherwise.
    """
    return not path_exists(pred_path) or pred_path.stat().st_size == 0


def reconstruct_volume(pred_masks_dir: Path, reference_volume: Path, output_path: Path, plane: str) -> np.ndarray:
    """Reconstructs a 3D NIfTI volume from 2D predicted mask slices.

    Args:
        pred_masks_dir: Directory containing the predicted mask PNG files.
        reference_volume: Path to the ground truth NIfTI file used as shape/affine reference.
        output_path: Path where the reconstructed NIfTI volume will be saved.
        plane: Anatomical plane ('axial', 'coronal', 'sagittal').

    Returns:
        Reconstructed 3D volume as a float32 NumPy array.
    """
    shape_original, affine = load_nifti_reference(reference_volume)
    volume = np.zeros(shape_original, dtype=np.float32)
    indices = extract_png_indices(pred_masks_dir)

    for filename, idx in indices:
        pred_mask_path = Path(pred_masks_dir) / filename
        pred_mask_array = load_and_preprocess_image(pred_mask_path)

        validate_slice(idx, pred_mask_array, shape_original, plane)
        insert_slice(volume, pred_mask_array, idx, plane)

    save_volume(volume, affine, output_path)
    return volume


# ======================================
#              PROCESSING
# ======================================


def process_patient_volume(patient_id: str, config: ConfigReconstruction, paths_dir: dict[str, Path] | None = None) -> StageResult:
    """Executes the volume reconstruction process for an individual patient.

    Checks whether the volume already exists and is valid, then reconstructs and
    validates it if needed.

    Args:
        patient_id: Patient identifier string.
        config: ConfigReconstruction instance providing model and directory settings.
        paths_dir: Dictionary of paths (pred_vol, gt_vol, pred_masks). Defaults to
            config patient paths if None.

    Returns:
        StageResult.COMPLETED if the volume was reconstructed, StageResult.SKIPPED
        if skipped (already valid).

    Raises:
        RuntimeError: If the reconstructed volume fails validation.
    """
    # If no directories are provided → patient mode → use config directories
    if paths_dir is None:
        paths_dir = {
            "pred_vol": config.patient_pred_vol,
            "gt_vol": config.patient_gt_vol,
            "pred_masks": config.patient_pred_masks,
        }

    patient_pred_vol = paths_dir["pred_vol"]
    patient_gt_vol = paths_dir["gt_vol"]
    patient_pred_masks = paths_dir["pred_masks"]

    # Check if a reconstructed volume already exists
    if not needs_reconstruction(patient_pred_vol):

        # If it exists, validate it against the ground truth
        if not is_valid_reconstruction(
            pred_vol_path=patient_pred_vol,
            gt_vol_path=patient_gt_vol,
        ):
            # If invalid, mark for reconstruction
            logger.warning(
                f"⚠️ Invalid reconstruction for {patient_id}, must be redone."
            )
            reconstruction_needed = True
        else:
            return StageResult.SKIPPED
    else:
        reconstruction_needed = True

    # Reconstruct and validate the result
    if reconstruction_needed:
        reconstruct_volume(
            pred_masks_dir=patient_pred_masks,
            reference_volume=patient_gt_vol,
            output_path=patient_pred_vol,
            plane=config.model.plane,
        )
        if not is_valid_reconstruction(
            pred_vol_path=patient_pred_vol, gt_vol_path=patient_gt_vol
        ):
            raise RuntimeError(f"Validation failed for {patient_id}.")
        return StageResult.COMPLETED


def build_paths(patient_id: str, config: ConfigReconstruction) -> dict[str, Path]:
    """Builds the predicted volume, GT volume, and pred_masks paths for a patient.

    Args:
        patient_id: Patient identifier string.
        config: ConfigReconstruction instance providing directory and plane settings.

    Returns:
        Dictionary with keys 'pred_vol', 'gt_vol', and 'pred_masks' mapping to Path objects.
    """
    root_pred_vols = config.pred_vols_fold_dir / patient_id
    root_gt = config.gt_dir / patient_id
    root_dataset = config.dataset_fold_dir / patient_id / config.plane
    pred_masks_dir = root_dataset / "pred_masks"

    return {
        "pred_vol": root_pred_vols / f"{patient_id}_{config.plane}{EXT_NIFTI}",
        "gt_vol": root_gt / f"{patient_id}{MASK_SUFFIX}{EXT_NIFTI}",
        "pred_masks": pred_masks_dir,
    }


def reconstruct_volumes_for_patients(input_dir: Path, config: ConfigReconstruction) -> StageResult:
    """Executes the volume reconstruction process for all patients in a directory.

    Args:
        input_dir: Directory containing patient subdirectories to process.
        config: ConfigReconstruction instance providing model and directory settings.

    Returns:
        StageResult.COMPLETED if all patients were processed, StageResult.SKIPPED
        if all were skipped, or StageResult.PARTIAL if there was a mix.
    """
    patients = list_patients(input_dir)

    results = []
    for patient_id in patients:
        patient_paths = build_paths(patient_id, config)
        try:
            reconstructed = process_patient_volume(
                patient_id=patient_id, config=config, paths_dir=patient_paths
            )
            results.append(reconstructed)
        except Exception as e:
            logger.warning(
                f"⚠️ Error reconstructing volumes for {patient_id}, skipping: {e}.",
            )
            continue

    return evaluate_results(results)


# ======================================
#               MAIN FLOW
# ======================================


def run_volume_flow(config: ConfigReconstruction, clean: bool, verbose: bool = False) -> None:
    """Executes the main volume reconstruction flow.

    Args:
        config: ConfigReconstruction instance defining the reconstruction configuration.
        clean: If True, deletes existing reconstructed volumes before regenerating.
        verbose: If True, logs a header message at the start of execution.
    """

    if verbose:
        if config.is_individual_patient:
            str_header = f"patient {config.patient}"
        elif config.single_fold:
            str_header = f"group {config.group}"
        else:
            str_header = f"fold {config.fold_test}"

        logger.header(f"\n🧱 Reconstructing volume(s) for {str_header}.")

    # Clean if requested
    if clean:
        if verbose:
            logger.info(f"♻️ Cleaning previous volumes.")
        config.clean()

    # Verify paths
    config.verify_paths()

    # Patient execution
    if config.is_individual_patient:
        patient_id = config.patient.id
        reconstructed = process_patient_volume(
            patient_id=patient_id, config=config
        )
        if reconstructed is StageResult.SKIPPED:
            logger.skip(f"⏩ Reconstructed volume already exists.")
        elif reconstructed is StageResult.COMPLETED:
            logger.info(f"✅ Volume reconstructed and validated successfully.")
        else:
            logger.warning(f"⚠️ Unknown status when reconstructing volume.")

    # Fold execution
    else:
        reconstructed = reconstruct_volumes_for_patients(
            input_dir=config.dataset_fold_dir, config=config
        )
        if config.k_folds == 1:
            if reconstructed is StageResult.SKIPPED:
                logger.skip(f"⏩ Volumes for {config.group} already exist.")
            elif reconstructed is StageResult.COMPLETED:
                logger.info(f"🆗 Volumes for {config.group} reconstructed successfully.")
            elif reconstructed is StageResult.PARTIAL:
                logger.info(
                    f"🔁 Volumes for {config.group} partially updated."
                )
            else:
                logger.warning("⚠️ Unknown status when reconstructing volumes.")

        else:
            log_fold_status(
                logger=logger,
                result=reconstructed,
                fold=config.fold_test,
            )


# ======================================
#           CLI AND EXECUTION
# ======================================


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parses command-line arguments for the volume reconstruction script.

    Args:
        argv: Argument list to parse. Defaults to sys.argv[1:] if None.

    Returns:
        Namespace with the parsed CLI arguments.
    """
    if argv is None:
        argv = sys.argv[1:]

    parser = argparse.ArgumentParser(
        description="Reconstruct 3D NIfTI volumes from 2D YOLO prediction masks.",
    )
    parser.add_argument(
        "--plane",
        type=str,
        required=True,
        choices=["axial", "coronal", "sagittal"],
        metavar="[axial, coronal, sagittal]",
        help="Anatomical extraction plane.",
    )
    parser.add_argument(
        "--modality",
        nargs="+",
        choices=["T1", "T2", "FLAIR"],
        default=["T1", "T2", "FLAIR"],
        metavar="[T1, T2, FLAIR]",
        help="MRI modality or modalities. Defaults to all.",
    )
    parser.add_argument(
        "--num_slices",
        type=int_or_percentile,
        required=True,
        metavar="<num_slices>",
        help="Number of extracted slices (fixed value or percentile).",
    )
    parser.add_argument(
        "--enhancement",
        type=str,
        default=None,
        choices=list(ENHANCEMENTS),
        metavar="<enhancement>",
        help="Image enhancement algorithm applied. Defaults to None.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        required=True,
        metavar="<epochs>",
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--k_folds",
        type=int,
        default=1,
        metavar="<k_folds>",
        help="Number of folds for cross-validation. Defaults to 1.",
    )
    group = parser.add_mutually_exclusive_group(required=False)
    group.add_argument(
        "--fold_test",
        type=int,
        metavar="<fold_test>",
        help="Reconstruct volumes for the indicated fold, used as the test set.",
    )
    group.add_argument(
        "--patient_id",
        type=str,
        metavar="<patient_id>",
        help="Reconstruct volumes only for the specified patient.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        default=False,
        help="Clean previously reconstructed volumes.",
    )

    args = parser.parse_args(argv)

    # Validations
    if args.k_folds == 1 and args.fold_test is not None:
        parser.error("--fold_test must not be specified when --k_folds == 1.")
    if args.k_folds > 1 and args.fold_test is None and args.patient_id is None:
        parser.error(
            "--fold_test or --patient_id must be specified when k_folds > 1."
        )

    return args


def main(argv: list[str] | None = None) -> None:
    """CLI entry point: parses arguments and executes the volume reconstruction flow.

    Args:
        argv: Argument list to parse. Defaults to sys.argv[1:] if None.
    """
    args = parse_args(argv)

    model = Model(
        plane=args.plane,
        num_slices=args.num_slices,
        modality=args.modality,
        k_folds=args.k_folds,
        enhancement=args.enhancement,
    )

    patient = None
    if args.patient_id is not None:
        patient = Patient(
            id=args.patient_id,
            plane=model.plane,
            modality=model.modality,
            enhancement=model.enhancement,
        )
    config = ConfigReconstruction(
        model=model,
        epochs=args.epochs,
        patient=patient,
        fold_test=args.fold_test,
    )
    run_volume_flow(config=config, clean=args.clean, verbose=True)


def run_reconstruction_pipeline(
    model: Model, patient: Patient | None = None, fold_test: int | None = None, epochs: int = 50, clean: bool = False
) -> None:
    """Internal pipeline entry point: executes the volume reconstruction flow programmatically.

    Args:
        model: Model instance defining the reconstruction configuration.
        patient: Patient instance for individual execution, or None for fold mode.
        fold_test: Test fold index when using cross-validation, or None.
        epochs: Number of training epochs of the YOLO model.
        clean: If True, deletes existing reconstructed volumes before regenerating.
    """
    config = ConfigReconstruction(
        model=model,
        epochs=epochs,
        patient=patient,
        fold_test=fold_test,
    )
    run_volume_flow(
        config=config,
        clean=clean,
    )


if __name__ == "__main__":
    main()
